---
# Подготовка и настройка Intraservice
- name: Prepare and configure Intraservice
  hosts: all
  become: yes

  vars:
    intraservice_dir: /var/www/intraservice                   # Директория приложения
    agent_dir: /var/www/intraservice.agent                    # Директория агента
    download_dir: "/tmp/intraservice-install"                # Распакованная директория
    main_archive_name: "site.zip"                             # Имя основного архива
    agent_archive_name: "site-agent.zip"                      # Имя архива агента
    intraservice_url: "http://example.intraiservice.local"  # URL сайта
    agent_url: "http://example.agent.local"                  # URL агента

    db_host: "{{ db_host_var }}"
    db_port: "{{ db_port_var }}"
    db_name: "{{ db_name_var }}"
    db_user: "{{ db_user_var }}"
    db_pass: "{{ db_pass_var | quote }}"



  tasks:
    # Установка необходимого инструмента для распаковки ZIP-архивов
    - name: Install unzip utility
      apt:
        name: unzip
        update_cache: yes
        state: present

    # Распаковка основного дистрибутива
    - name: Unpack main distribution archive
      unarchive:
        src: "{{ download_dir }}/{{ main_archive_name }}"
        dest: "{{ intraservice_dir }}"
        remote_src: yes
      register: result_unpack_main

    # Распаковка агента
    - name: Unpack agent distribution archive
      unarchive:
        src: "{{ download_dir }}/{{ agent_archive_name }}"
        dest: "{{ agent_dir }}"
        remote_src: yes
      register: result_unpack_agent

    # Настраиваем права доступа к нужным директориям
    - name: Adjust folder permissions
      file:
        path: "{{ item }}"
        mode: '0777'
        recurse: yes
      with_items:
        - "{{ intraservice_dir }}/wwwroot/img"
        - "{{ intraservice_dir }}/wwwroot/tempfiles"
        - "{{ intraservice_dir }}/temp"

    # Генерируем конфигурационные файлы
    - name: Generate appsettings.json for Intraservice
      template:
        src: appsettings.json.j2
        dest: "{{ intraservice_dir }}/appsettings.json"

    - name: Generate appsettings.json for Agent
      template:
        src: appsettings.json.j2
        dest: "{{ agent_dir }}/appsettings.json"
