---
# Playbook для скачивания архивов Intraservice
- hosts: all
  become: true
  gather_facts: false

  vars:
    download_dir: "/tmp/intraservice-install/"           # Временная директория для сохранения архивов
    main_archive_url: "https://storage.yandexcloud.net/intraservice-distr/5.4.7.site.zip"
    agent_archive_url: "https://storage.yandexcloud.net/intraservice-distr/5.4.7-linux-agent.zip"
    main_archive_name: "site.zip"
    agent_archive_name: "site-agent.zip"

  tasks:
    # Создание временной директории для скачивания
    - name: Create temporary directory for downloads
      file:
        path: "{{ download_dir }}"
        state: directory
        mode: '0755'

    # Загрузка основного дистрибутива
    - name: Download main distribution archive
      get_url:
        url: "{{ main_archive_url }}"
        dest: "{{ download_dir }}{{ main_archive_name }}"
        validate_certs: no

    # Загрузка агента
    - name: Download agent distribution archive
      get_url:
        url: "{{ agent_archive_url }}"
        dest: "{{ download_dir }}{{ agent_archive_name }}"
        validate_certs: no
