# vars_from_env.yml
- name: Load environment variables
  hosts: localhost
  connection: local
  tasks:
    - name: Read .env file
      ansible.builtin.shell: |
        set -o allexport
        source .env
        set +o allexport
        env | grep -E '^(INTRASERVICE|AGENT|DB_|DOWNLOAD)'
      register: env_output
      changed_when: false

    - name: Set facts from .env
      ansible.builtin.set_fact:
        env_vars: "{{ env_output.stdout_lines | items2dict(key_name='item', value_name='item', splitter='=') }}"
